config/routes.rb
Rails.application.routes.draw do
  get 'scms/index'
  get 'scms/use_reports'
  get 'scms/order_reports'
  get 'scms/delivery_reports'

  get 'use_reports/use_reports'
  get 'use_reports/use_reports_edit'

  resources :scms
  resources :use_reports

  root 'scms#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/scm.rb
class Scm < ApplicationRecord
	def get_toOrder
		if self.restock != nil
			if self.restock-practical_qty < 0#2 - 5 //reorder at 2, we have 5, we need to order -3
				0
			else self.restock-practical_qty
			end
		end
	end

	def practical_qty
		if self.in_shop != nil && self.ordered != nil && self.allocated != nil
			self.in_shop+self.ordered-self.allocated
		else
			0
		end
	end
end

app/models/use_report.rb
class UseReport < ApplicationRecord
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/scms_controller.rb
class ScmsController < ApplicationController
  before_action :set_scm, only: %i[ show edit update destroy ]

  # GET /scms or /scms.json
  def index
    @scms = Scm.all
  end

  # GET /scms/1 or /scms/1.json
  def show
  end

  # GET /scms/new
  def new
    @scm = Scm.new
  end

  # GET /scms/1/edit
  def edit
  end

  # POST /scms or /scms.json
  def create
    @scm = Scm.new(scm_params)

    respond_to do |format|
      if @scm.save
        format.html { redirect_to scms_url(@scm), notice: "Scm was successfully created." }
        #format.html { redirect_back fallback_location: scms_url(@scm)}
        format.json { render :show, status: :created, location: @scm }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @scm.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scms/1 or /scms/1.json
  def update
    respond_to do |format|
      if @scm.update(scm_params)
        format.html { redirect_to scm_url(@scm), notice: "Scm was successfully updated." }
        format.json { render :show, status: :ok, location: @scm }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @scm.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scms/1 or /scms/1.json
  def destroy
    @scm.destroy

    respond_to do |format|
      format.html { redirect_to scms_url(@scm), notice: "Scm was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scm
      @scm = Scm.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def scm_params
      params.require(:scm).permit(:item_name, :part_number, :description, :in_shop, :allocated, :ordered, :restock, :stock_cap, :category, :verified_when, :verified_by, :unit, :supplier0, :supplier1, :supplier2, :supplier3, :supplier4, :supplier5, :supplier6, :supplier7, :supplier8, :supplier9)
    end
end

app/controllers/use_reports_controller.rb
class UseReportsController < ApplicationController

	def use_reports
		@reports = UseReport.all
	end

	# GET /use_reports/1 or /scms/1.json
  	def show
  	end

  	# GET /use_reports/new
  	def new
    @scm = Scm.new
 	 end

  	# GET /use_reports/1/edit
  	def edit
  	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/scms_helper.rb
module ScmsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gopher</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link rel="stylesheet" type="text/css" href="application.css"/>

  </head>

  <body style="background-color:#181818">
    <%= render 'scms/header' %>
    <%= yield %>
    <%= render 'scms/footer' %>
  </body>
</html>

app/views/scms/_all_items.html.erb
<% @scms.each do |scm| %>
  <tr id="<%= dom_id scm %>">
    <td> <%= scm.item_name %> </td>
    <td> <%= scm.part_number %> </td>
    <td> <%= scm.in_shop %> </td>
    <td> <%= scm.get_toOrder %> </td>
    <td class="standard"> <%= link_to "Edit", edit_scm_path(scm) %> </td>
    <td class="deleteBurrito"> <%= link_to "Delete", scm_url(scm) %> </td>
  </tr>
<% end %>

app/views/scms/_form.html.erb
<div class="pagecontents">
<%= form_with(model: scm) do |form| %>
  <% if scm.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(scm.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% scm.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="editForm">
  <div class="inline">
  <div class="block">
    <div>
      <%= form.label :item_name, style: "display: block" %>
      <%= form.text_field :item_name %>
    </div>
    <div>
      <%= form.label :description, style: "display: block" %>
      <%= form.text_area :description %>
    </div>
  </div>

  <div class="block">
    <div>
      <%= form.label :in_shop, style: "display: block" %>
      <%= form.number_field :in_shop %>
    </div>
    <div>
      <%= form.label :allocated, style: "display: block" %>
      <%= form.number_field :allocated %>
    </div>
    <div>
      <%= form.label :ordered, style: "display: block" %>
      <%= form.number_field :ordered %>
    </div>
    <div>
      <%= form.label :restock, style: "display: block" %>
      <%= form.number_field :restock %>
    </div>
    <div>
      <%= form.label :stock_cap, style: "display: block" %>
      <%= form.number_field :stock_cap %>
    </div>
  </div>

  <div class="block">
    <div>
      <%= form.label :category, style: "display: block" %>
      <%= form.text_field :category %>
    </div>
    <div>
      <%= form.label :part_number, style: "display: block" %>
      <%= form.text_field :part_number %>
    </div>
    <div>
      <%= form.label :unit, style: "display: block" %>
      <%= form.text_field :unit %>
    </div>
    <div>
      <%= form.label :verified_by, style: "display: block" %>
      <%= form.text_field :verified_by %>
    </div>
    <div>
      <%= form.label :verified_when, style: "display: block" %>
      <%= form.date_field :verified_when %>
    </div>
  </div>

  <div class="block">
    <div>
      <%= form.label :supplier0, style: "display: block" %>
      <%= form.text_field :supplier0 %>
    </div>
    <div>
      <%= form.label :supplier1, style: "display: block" %>
      <%= form.text_field :supplier1 %>
    </div>
    <div>
      <%= form.label :supplier2, style: "display: block" %>
      <%= form.text_field :supplier2 %>
    </div>
    <div>
      <%= form.label :supplier3, style: "display: block" %>
      <%= form.text_field :supplier3 %>
    </div>
    <div>
      <%= form.label :supplier4, style: "display: block" %>
      <%= form.text_field :supplier4 %>
    </div>
  </div>

  <div class="block">
    <div>
      <%= form.label :supplier5, style: "display: block" %>
      <%= form.text_field :supplier5 %>
    </div>
    <div>
      <%= form.label :supplier6, style: "display: block" %>
      <%= form.text_field :supplier6 %>
    </div>
    <div>
      <%= form.label :supplier7, style: "display: block" %>
      <%= form.text_field :supplier7 %>
    </div>
    <div>
      <%= form.label :supplier8, style: "display: block" %>
      <%= form.text_field :supplier8 %>
    </div>
    <div>
      <%= form.label :supplier9, style: "display: block" %>
      <%= form.text_field :supplier9 %>
    </div>
  </div>
</div>
</div>
<div class="sdButtons">
<%= form.submit "Submit New Entry", :class => "saveButton"%>
<a href="/"> <%= button_to "Cancel", scms_path, :class => "cancelBurrito"%> </a>
<% end %>
</div>
</div>
<!-- scms_index_path is legit -->

app/views/scms/_header.html.erb
<nav class="navbar">
	<ul>
		<div class="standard">
		<div class="menu">	
				<%= link_to 'In Stock', root_path, class:'navbar_item' %>
				<%= link_to 'Use Reports', use_reports_use_reports_path, class:'navbar_item' %>
				<%= link_to 'Order Reports', scms_order_reports_path, class:'navbar_item' %>
				<%= link_to 'Delivery Reports', scms_delivery_reports_path, class:'navbar_item' %>
		</div>
	</div>
	</ul>
</nav>

app/views/scms/_scm.html.erb
<tr id="<%= dom_id scm %>">
  <td> <%= scm.item_name %> </td>
  <td> <%= scm.part_number %> </td>
  <td> <%= scm.description %> </td>
  <td> <%= scm.in_shop %> </td>
  <td> <%= scm.allocated %> </td>
  <td> <%= scm.ordered %> </td>
  <td> <%= scm.restock %> </td>
  <td> <%= scm.stock_cap %> </td>
  <td> <%= scm.category %> </td>
  <td> <%= scm.verified_when %> </td>
  <td> <%= scm.verified_by %> </td>
  <td> <%= scm.unit %> </td>
  <td> <%= scm.supplier0 %> </td>
  <td> <%= scm.supplier1 %> </td>
  <td> <%= scm.supplier2 %> </td>
  <td> <%= scm.supplier3 %> </td>
  <td> <%= scm.supplier4 %> </td>
  <td> <%= scm.supplier5 %> </td>
  <td> <%= scm.supplier6 %> </td>
  <td> <%= scm.supplier7 %> </td>
  <td> <%= scm.supplier8 %> </td>
  <td> <%= scm.supplier9 %> </td>
</tr>

app/views/scms/delivery_reports.erb
<h1 class="goldtext">New Delivery Report</h1>

app/views/scms/edit.html.erb
<h1 class="goldtext">Editing scm</h1>

<div>
  <%= link_to "Back to items", root_path %>
</div>
<br>

<%= render "form", scm: @scm %>

app/views/scms/index.html.erb
<p style="color: green"><%= notice %></p>

<p class="Goteem">Deez Nuts</p>

<div>
  <table id="items">
    <thead>
      <th>Item Name</th>
      <th>Part Number</th>
      <th>In Stock</th>
      <th>Needed</th>
    </thead>
    <tbody>
      <div class="dataEntry">
        <%= render "form", scm: Scm.new %>
      </div>
      <div class="scms">
      <%= render 'all_items' %>
    </div>
    </tbody>
  </table>
</div>


<!-- %= link_to "Show this scm", scm %> -->

app/views/scms/new.html.erb
<h1 class="goldtext">New Item</h1>

<%= render "form", scm: @scm %>

<br>

app/views/scms/order_reports.erb
<h1 class="goldtext">New Order Report</h1>

app/views/scms/show.html.erb
<div class="editMenuContainer">
  <div class="backToIndex">
   <button type="button"> <%= link_to "Back to main", scms_path %> </button>
  </div>
  <div class="deleteEntry">
    <%= button_to "Delete", @scm, method: :delete %>
  </div>
</div>

app/views/use_reports/use_reports.html.erb
<h1 class="goldtext" style="text-align: center;">
	Page Header Here lol(i) ;)
</h1>


<table class="useReportsTable">
	<tr class="useReportsTable">
		<th class="useReportsTable">P.O</th>
		<th class="useReportsTable">Date</th>
		<th class="useReportsTable">Created By</th>
		<th class="useReportsTable">Squiggles</th>
	</tr>
	<tr class="useReportsTable">
		<td class="useReportsTable">P.O Entry #1</td>
		<td class="useReportsTable">Date Entry #1</td>
		<td class="useReportsTable">Made By Entry #1</td>
		<td class="useReportsTable">Goat #1</td>
	</tr>
	<tr class="useReportsTable">
		<td class="useReportsTable">P.O Entry #2</td>
		<td class="useReportsTable">Date Entry #2</td>
		<td class="useReportsTable">Made By Entry #2</td>
		<td class="useReportsTable">Goat #2</td>
	</tr>
	<tr class="useReportsTable">
		<td class="useReportsTable">P.O Entry #3</td>
		<td class="useReportsTable">Date Entry #3</td>
		<td class="useReportsTable">Made By Entry #3</td>
		<td class="useReportsTable">Goat #3</td>
	</tr>
</table>



<script>

var tables = document.getElementAttribute("table");

for (var i = 0; i < tables.length; i++) {

	var table = tables[i];

	table.setAttribute("id", i + 1);

	/* The line below will also give id
	dynamically to the tables */
	//table.id = i+1;
}

</script>

app/views/use_reports/use_reports_edit.erb
<h1 class="goldtext">Edits page</h1>